// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmsGnd7vz4-T_GGpCdKdL_0_v4790Cw-E',
    appId: '1:71854392536:web:3478de769e8227c805c3ad',
    messagingSenderId: '71854392536',
    projectId: 'chat-e1131',
    authDomain: 'chat-e1131.firebaseapp.com',
    databaseURL: 'https://chat-e1131-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-e1131.appspot.com',
    measurementId: 'G-RB90DQCGW1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJpzIm0a4XsUGnXV3IV8XS26llM1T-hFc',
    appId: '1:71854392536:android:e3e4c8dbe7762a7205c3ad',
    messagingSenderId: '71854392536',
    projectId: 'chat-e1131',
    databaseURL: 'https://chat-e1131-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-e1131.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACaGpBCzh_hA0qqsJWslBEGtWIsWHM9L0',
    appId: '1:71854392536:ios:e4f01103462f9b1605c3ad',
    messagingSenderId: '71854392536',
    projectId: 'chat-e1131',
    databaseURL: 'https://chat-e1131-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-e1131.appspot.com',
    iosBundleId: 'com.example.chatapps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACaGpBCzh_hA0qqsJWslBEGtWIsWHM9L0',
    appId: '1:71854392536:ios:e4f01103462f9b1605c3ad',
    messagingSenderId: '71854392536',
    projectId: 'chat-e1131',
    databaseURL: 'https://chat-e1131-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-e1131.appspot.com',
    iosBundleId: 'com.example.chatapps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmsGnd7vz4-T_GGpCdKdL_0_v4790Cw-E',
    appId: '1:71854392536:web:798b80df4d3148d105c3ad',
    messagingSenderId: '71854392536',
    projectId: 'chat-e1131',
    authDomain: 'chat-e1131.firebaseapp.com',
    databaseURL: 'https://chat-e1131-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-e1131.appspot.com',
    measurementId: 'G-4FCTY9164V',
  );

}